// Code generated by "stringer -type=PacketType"; DO NOT EDIT.

package proto

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[PacketTypeKeepAlive-0]
	_ = x[PacketTypeConnectionAccepted-1]
	_ = x[PacketTypeConnectionRefused-2]
	_ = x[PacketTypeDataUpdate-3]
	_ = x[PacketTypeMapUpdate-4]
	_ = x[PacketTypeCommand-5]
	_ = x[PacketTypeCommandResult-6]
	_ = x[PacketTypeCount-7]
}

const _PacketType_name = "PacketTypeKeepAlivePacketTypeConnectionAcceptedPacketTypeConnectionRefusedPacketTypeDataUpdatePacketTypeMapUpdatePacketTypeCommandPacketTypeCommandResultPacketTypeCount"

var _PacketType_index = [...]uint8{0, 19, 47, 74, 94, 113, 130, 153, 168}

func (i PacketType) String() string {
	if i >= PacketType(len(_PacketType_index)-1) {
		return "PacketType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _PacketType_name[_PacketType_index[i]:_PacketType_index[i+1]]
}
